CREATE TABLE [dbo].[EventTeam](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EventKey] [nvarchar](50) NULL,
	[TeamNumber] [int] NULL,
 CONSTRAINT [PK_EventTeam] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_EventTeam_EventKey_TeamNumber] ON [dbo].[EventTeam]
(
	[EventKey] ASC,
	[TeamNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
