CREATE TABLE [dbo].[EventTeam](
	[Id] [int] NOT NULL,
	[EventKey] [varchar](50) NULL,
	[TeamNumber] [int] NULL,
 CONSTRAINT [PK_EventTeam] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
